// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The sidebar is generated from each notebook's _metadata.json so the docs
// reading side shows the same human titles and drag-and-drop order as the Write
// app — instead of Docusaurus's filename-based autogeneration.

import { readNotebooksFromDisk } from './src/lib/notebooksFs.js';

function buildTutorialSidebar() {
  const notebooks = readNotebooksFromDisk('docs');

  return notebooks.map(nb => {
    if (!nb.hasMetadata) {
      // No metadata to order/label by — fall back to autogeneration for this dir.
      return {
        type: 'category',
        label: nb.label,
        items: [{ type: 'autogenerated', dirName: nb.dir }],
      };
    }
    return {
      type: 'category',
      label: nb.label,
      collapsed: false,
      items: nb.notes.map(note => ({ type: 'doc', id: note.id, label: note.title })),
    };
  });
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: buildTutorialSidebar(),
};

export default sidebars;
