// Shared inline-style object for the notebook workspace components. Extracted
// verbatim from the original page (dead keys and a duplicate `previewTitle`
// removed) so every tile, panel, and modal reads from one source of truth.

import type { CSSProperties } from 'react';

export const s: Record<string, CSSProperties> = {
  gate: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '70vh',
    padding: 24,
  },
  gateCard: {
    maxWidth: 460,
    width: '100%',
    padding: 32,
    border: '1px solid var(--ifm-color-emphasis-300)',
    borderRadius: 12,
    backgroundColor: 'var(--ifm-background-surface-color)',
    position: 'relative',
  },
  gateClose: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 28,
    height: 28,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 14,
    color: 'var(--ifm-color-emphasis-500)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
  },
  workspace: {
    display: 'flex',
    height: 'calc(100vh - 60px)',
    overflow: 'hidden',
    position: 'relative',
  },
  sidebar: {
    width: 240,
    flexShrink: 0,
    borderRight: '1px solid var(--ifm-color-emphasis-300)',
    backgroundColor: 'var(--ifm-background-surface-color)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '14px 16px',
    borderBottom: '1px solid var(--ifm-color-emphasis-300)',
    fontWeight: 700,
    fontSize: 11,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--ifm-color-emphasis-600)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notebookList: {
    flex: 1,
    overflowY: 'auto',
    padding: '6px 0',
  },
  notebookItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    padding: '8px 16px',
    border: 'none',
    borderLeft: '3px solid transparent',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 14,
    color: 'var(--ifm-font-color-base)',
    textAlign: 'left',
  },
  notebookItemActive: {
    borderLeft: '3px solid var(--ifm-color-primary)',
    backgroundColor: 'var(--ifm-color-emphasis-100)',
    fontWeight: 600,
    color: 'var(--ifm-color-primary)',
  },
  notebookIcon: { fontSize: 16, flexShrink: 0 },
  notebookLabel: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  sidebarFooter: {
    padding: '12px 16px',
    borderTop: '1px solid var(--ifm-color-emphasis-300)',
  },
  main: {
    flex: 1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  panel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 24px',
    borderBottom: '1px solid var(--ifm-color-emphasis-300)',
    flexShrink: 0,
  },
  syncBarTrack: {
    height: 3,
    width: '100%',
    backgroundColor: 'transparent',
    flexShrink: 0,
    overflow: 'hidden',
  },
  syncBarFill: {
    height: '100%',
    backgroundColor: 'var(--ifm-color-primary)',
    borderRadius: 2,
  },
  noteListBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 20px',
  },
  noteItem: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    border: '1px solid var(--ifm-color-emphasis-200)',
    borderRadius: 8,
    background: 'var(--ifm-background-surface-color)',
    fontSize: 14,
    color: 'var(--ifm-font-color-base)',
    textAlign: 'left',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    overflow: 'hidden',
  },
  noteItemExpanded: {
    borderColor: 'var(--ifm-color-primary)',
    // Soft outer glow ("ring") instead of a hard focus outline.
    boxShadow: '0 0 0 3px rgba(96,165,250,0.22), 0 6px 22px rgba(17,24,39,0.07)',
  },
  noteItemDragging: {
    opacity: 0.4,
  },
  dropSeparator: {
    height: 8,
    position: 'relative',
    flexShrink: 0,
  },
  dropSeparatorLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    height: 3,
    borderRadius: 2,
    backgroundColor: 'transparent',
    transition: 'background-color 0.1s ease',
    pointerEvents: 'none',
  },
  dropSeparatorLineActive: {
    // Solid line for the drag-drop target (overrides the hover gradient + fade).
    background: 'var(--ifm-color-primary)',
    opacity: 1,
    boxShadow: '0 0 0 1px var(--ifm-color-primary)',
  },
  addAffordance: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: 6,
  },
  addBtn: {
    // Floating micro "+" container that rides the hover gradient line.
    pointerEvents: 'auto',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 26,
    height: 26,
    padding: 0,
    fontSize: 18,
    lineHeight: 1,
    fontWeight: 600,
    color: '#fff',
    background: 'var(--ifm-color-primary)',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    boxShadow: '0 2px 10px rgba(26,86,219,0.4)',
    whiteSpace: 'nowrap',
  },
  draftItem: {
    boxShadow: '0 2px 14px rgba(0,0,0,0.10)',
  },
  btnDisabled: {
    opacity: 0.45,
    cursor: 'default',
  },
  emptyZone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    border: '1.5px dashed var(--ifm-color-emphasis-300)',
    borderRadius: 10,
    cursor: 'pointer',
    position: 'relative',
    gap: 0,
  },
  emptyPrompt: {
    position: 'absolute',
    fontSize: 14,
    color: 'var(--ifm-color-emphasis-500)',
    transition: 'opacity 0.12s ease',
  },
  emptyAddBtn: {
    opacity: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 18px',
    fontSize: 14,
    fontWeight: 600,
    color: '#fff',
    background: 'var(--ifm-color-primary)',
    border: '1px solid var(--ifm-color-primary)',
    borderRadius: 8,
    cursor: 'pointer',
  },
  tileUpdated: {
    flexShrink: 0,
    marginLeft: 'auto',
    paddingLeft: 12,
    fontSize: 11,
    fontWeight: 400,
    color: 'var(--ifm-color-emphasis-500)',
    whiteSpace: 'nowrap',
    fontVariantNumeric: 'tabular-nums',
  },
  dragHandle: {
    cursor: 'grab',
    color: 'var(--ifm-color-emphasis-400)',
    fontSize: 16,
    lineHeight: 1,
    flexShrink: 0,
    userSelect: 'none',
    padding: '0 2px',
  },
  tileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    padding: '9px 14px',
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  tileChevron: {
    fontSize: 12,
    color: 'var(--ifm-color-emphasis-500)',
    flexShrink: 0,
    transition: 'transform 0.18s ease',
    display: 'inline-block',
  },
  tileBody: {
    borderTop: '1px solid var(--ifm-color-emphasis-200)',
    padding: '14px 16px',
    cursor: 'default',
    backgroundColor: 'var(--ifm-background-color)',
    display: 'flex',
    flexDirection: 'column',
  },
  tileToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 8,
  },
  tilePreview: {
    lineHeight: 1.7,
    fontSize: 15,
  },
  tileTextarea: {
    flex: 'none',
    height: 'calc(100vh - 280px)',
    minHeight: 300,
  },
  noteIcon: { fontSize: 16, flexShrink: 0 },
  deleteBtn: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: 14,
    opacity: 0,
    padding: '2px 4px',
    borderRadius: 4,
    color: 'var(--ifm-color-emphasis-500)',
    flexShrink: 0,
  },
  btnSeparator: {
    width: 1,
    height: 20,
    backgroundColor: 'var(--ifm-color-emphasis-300)',
    flexShrink: 0,
  },
  btnDanger: {
    backgroundColor: '#e53e3e',
    color: '#fff',
    borderColor: '#e53e3e',
  },
  btnSaved: {
    backgroundColor: 'transparent',
    color: 'var(--ifm-color-emphasis-500)',
    borderColor: 'var(--ifm-color-emphasis-300)',
    cursor: 'default',
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
    fontSize: 14,
  },
  crumbMuted: {
    color: 'var(--ifm-color-emphasis-500)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: 160,
    flexShrink: 0,
  },
  crumbSep: { color: 'var(--ifm-color-emphasis-400)', flexShrink: 0 },
  crumbCurrent: {
    fontWeight: 600,
    color: 'var(--ifm-font-color-base)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  unsavedBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 600,
    color: '#b45309',
    backgroundColor: 'rgba(245,158,11,0.14)',
    borderRadius: 10,
    padding: '2px 8px',
  },
  unsavedDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: '#d97706',
  },
  segmented: {
    display: 'inline-flex',
    border: '1px solid var(--ifm-color-emphasis-300)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  segment: {
    padding: '6px 12px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--ifm-color-emphasis-600)',
    lineHeight: 1.4,
  },
  segmentActive: {
    backgroundColor: 'var(--ifm-color-primary)',
    color: '#fff',
  },
  editorBody: {
    flex: 1,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  input: {
    padding: '8px 12px',
    fontSize: 14,
    border: '1px solid var(--ifm-color-emphasis-300)',
    borderRadius: 6,
    backgroundColor: 'var(--ifm-background-color)',
    color: 'var(--ifm-font-color-base)',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  titleInput: {
    fontSize: 20,
    fontWeight: 600,
    marginBottom: 12,
    border: 'none',
    borderBottom: '2px solid var(--ifm-color-emphasis-200)',
    borderRadius: 0,
    padding: '8px 0',
  },
  textarea: {
    flex: 1,
    padding: '12px',
    fontSize: 14,
    lineHeight: 1.7,
    border: '1px solid var(--ifm-color-emphasis-200)',
    borderRadius: 6,
    backgroundColor: 'var(--ifm-background-color)',
    color: 'var(--ifm-font-color-base)',
    fontFamily: 'var(--ifm-font-family-monospace)',
    resize: 'none',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 200,
  },
  btn: {
    padding: '7px 14px',
    borderRadius: 6,
    border: '1px solid transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.4,
  },
  btnPrimary: {
    backgroundColor: 'var(--ifm-color-primary)',
    color: '#fff',
    borderColor: 'var(--ifm-color-primary)',
  },
  btnGhost: {
    backgroundColor: 'transparent',
    color: 'var(--ifm-color-emphasis-600)',
    borderColor: 'transparent',
  },
  btnOutline: {
    backgroundColor: 'transparent',
    color: 'var(--ifm-color-primary)',
    borderColor: 'var(--ifm-color-primary)',
  },
  label: {
    display: 'block',
    marginBottom: 6,
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--ifm-color-emphasis-700)',
  },
  hint: {
    padding: '12px 16px',
    fontSize: 13,
    color: 'var(--ifm-color-emphasis-500)',
    lineHeight: 1.6,
  },
  statusText: {
    fontSize: 13,
    color: 'var(--ifm-color-emphasis-600)',
  },
  modalOverlay: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
    backdropFilter: 'blur(2px)',
  },
  modalCard: {
    backgroundColor: 'var(--ifm-background-surface-color)',
    border: '1px solid var(--ifm-color-emphasis-300)',
    borderRadius: 10,
    padding: '24px 28px',
    minWidth: 300,
    maxWidth: 380,
    boxShadow: '0 12px 40px rgba(0,0,0,0.2)',
  },
  modalProgressTrack: {
    height: 6,
    backgroundColor: 'var(--ifm-color-emphasis-200)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  conflictBanner: {
    padding: '10px 14px',
    backgroundColor: 'rgba(245,158,11,0.12)',
    border: '1px solid rgba(245,158,11,0.5)',
    borderRadius: 6,
    marginBottom: 10,
    fontSize: 13,
    lineHeight: 1.5,
    flexShrink: 0,
  },
  previewTitle: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid var(--ifm-color-emphasis-200)',
  },
  markdownPreview: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 16px',
    border: '1px solid var(--ifm-color-emphasis-200)',
    borderRadius: 6,
    lineHeight: 1.7,
    fontSize: 15,
  },
  forgetBtn: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: '50%',
    border: '1px solid var(--ifm-color-emphasis-300)',
    background: 'var(--ifm-background-surface-color)',
    cursor: 'pointer',
    fontSize: 16,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.6,
  },
  tagRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    position: 'relative',
  },
  tagChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--ifm-color-primary-darker)',
    backgroundColor: 'var(--ifm-color-primary-lightest)',
    borderRadius: 10,
    padding: '2px 8px',
    whiteSpace: 'nowrap',
  },
  tagChipSmall: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    fontSize: 10,
    fontWeight: 500,
    color: 'var(--ifm-color-primary-darker)',
    backgroundColor: 'var(--ifm-color-primary-lightest)',
    borderRadius: 8,
    padding: '1px 6px',
    whiteSpace: 'nowrap',
  },
  tagChipRemove: {
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    padding: 0,
    fontSize: 12,
    lineHeight: 1,
    color: 'inherit',
    opacity: 0.7,
  },
  tagInput: {
    flex: 1,
    minWidth: 120,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    color: 'var(--ifm-font-color-base)',
    fontSize: 13,
    padding: '4px 0',
  },
  tagSuggest: {
    position: 'absolute',
    top: '100%',
    left: 0,
    zIndex: 30,
    minWidth: 180,
    maxHeight: 200,
    overflowY: 'auto',
    marginTop: 4,
    padding: 4,
    border: '1px solid var(--ifm-color-emphasis-300)',
    borderRadius: 6,
    backgroundColor: 'var(--ifm-background-surface-color)',
    boxShadow: '0 4px 14px rgba(0,0,0,0.12)',
  },
  tagSuggestItem: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    border: 'none',
    background: 'none',
    cursor: 'pointer',
    padding: '5px 8px',
    borderRadius: 4,
    fontSize: 13,
    color: 'var(--ifm-font-color-base)',
  },
};
